import { useCallback, useEffect, useState } from "react";
import { useAuth } from "../auth/auth-context";
import { archiveContent, contentId, loadContent, saveContent, uploadContentImage } from "../content/content-service";

const blankGallery=()=>({title:"",caption:"",src:"",storagePath:"",order:0,visible:true,active:true});
const blankPair=()=>({title:"",description:"",category:"",before:"",after:"",beforePath:"",afterPath:"",order:0,visible:true,active:true});
const extension=file=>file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";
export default function AdminMedea(){const{user,logout}=useAuth();const[gallery,setGallery]=useState([]);const[pairs,setPairs]=useState([]);const[galleryForm,setGalleryForm]=useState(blankGallery);const[pairForm,setPairForm]=useState(blankPair);const[galleryId,setGalleryId]=useState(null);const[pairId,setPairId]=useState(null);const[galleryFile,setGalleryFile]=useState(null);const[beforeFile,setBeforeFile]=useState(null);const[afterFile,setAfterFile]=useState(null);const[busy,setBusy]=useState(false);const load=useCallback(async()=>{const[g,b]=await Promise.all([loadContent("gallery",{admin:true}),loadContent("beforeAfter",{admin:true})]);setGallery(g);setPairs(b)},[]);useEffect(()=>{let active=true;void Promise.all([loadContent("gallery",{admin:true}),loadContent("beforeAfter",{admin:true})]).then(([g,b])=>{if(active){setGallery(g);setPairs(b)}});return()=>{active=false}},[]);
const submitGallery=async event=>{event.preventDefault();setBusy(true);try{const id=galleryId??contentId();let data={...galleryForm,order:Number(galleryForm.order)||0};if(galleryFile){const path=`gallery/${id}/main-${Date.now()}.${extension(galleryFile)}`;data={...data,src:await uploadContentImage(path,galleryFile),storagePath:path};}if(!data.src)throw new Error("Seleziona un’immagine.");await saveContent("gallery",id,data,{editing:Boolean(galleryId)});setGalleryForm(blankGallery());setGalleryId(null);setGalleryFile(null);await load();}catch(error){alert(error.message)}finally{setBusy(false)}};
const submitPair=async event=>{event.preventDefault();setBusy(true);try{const id=pairId??contentId();let data={...pairForm,order:Number(pairForm.order)||0};if(beforeFile){const path=`before-after/${id}/before/main-${Date.now()}.${extension(beforeFile)}`;data={...data,before:await uploadContentImage(path,beforeFile),beforePath:path};}if(afterFile){const path=`before-after/${id}/after/main-${Date.now()}.${extension(afterFile)}`;data={...data,after:await uploadContentImage(path,afterFile),afterPath:path};}if(!data.before||!data.after)throw new Error("Servono entrambe le immagini.");await saveContent("beforeAfter",id,data,{editing:Boolean(pairId)});setPairForm(blankPair());setPairId(null);setBeforeFile(null);setAfterFile(null);await load();}catch(error){alert(error.message)}finally{setBusy(false)}};
const archive=async(collectionName,id)=>{if(!confirm("Archiviare questo contenuto? Non sarà più visibile al pubblico ma resterà nello storico Admin."))return;await archiveContent(collectionName,id);await load()};
return <main style={s.page}><header style={s.header}><div><p style={s.kicker}>Pannello Admin</p><h1>Contenuti Medea</h1><p>{user.email}</p></div><button onClick={logout}>Logout</button></header><Editor title="Gallery" form={galleryForm} setForm={setGalleryForm} onSubmit={submitGallery} fileLabel={galleryId?"Sostituisci immagine":"Immagine"} setFile={setGalleryFile} busy={busy}/><Grid>{gallery.map(item=><Card key={item.id} item={item} images={[item.src]} onEdit={()=>{setGalleryId(item.id);setGalleryForm(item)}} onArchive={()=>archive("gallery",item.id)}/>)}</Grid><Editor title="Prima/Dopo" form={pairForm} setForm={setPairForm} onSubmit={submitPair} pairFiles setBefore={setBeforeFile} setAfter={setAfterFile} busy={busy}/><Grid>{pairs.map(item=><Card key={item.id} item={item} images={[item.before,item.after]} onEdit={()=>{setPairId(item.id);setPairForm(item)}} onArchive={()=>archive("beforeAfter",item.id)}/>)}</Grid></main>}
function Editor({title,form,setForm,onSubmit,fileLabel,setFile,pairFiles,setBefore,setAfter,busy}){const field=(key,label,type="text")=><label style={s.label}>{label}<input type={type} value={form[key]??""} onChange={event=>setForm(current=>({...current,[key]:type==="number"?Number(event.target.value):event.target.value}))} style={s.input}/></label>;return <form onSubmit={onSubmit} style={s.card}><h2>{title}</h2>{field("title","Titolo")}{"caption" in form?field("caption","Caption"):<>{field("description","Descrizione")}{field("category","Categoria/trattamento")}</>}{field("order","Ordine","number")}<label><input type="checkbox" checked={form.visible} onChange={e=>setForm(x=>({...x,visible:e.target.checked}))}/> Visibile</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm(x=>({...x,active:e.target.checked}))}/> Attivo</label>{pairFiles?<><label style={s.label}>Sostituisci Prima<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setBefore(e.target.files[0]??null)}/></label><label style={s.label}>Sostituisci Dopo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setAfter(e.target.files[0]??null)}/></label></>:<label style={s.label}>{fileLabel}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files[0]??null)}/></label>}<button disabled={busy}>{busy?"Salvataggio…":"Salva"}</button></form>}
function Grid({children}){return <section style={s.grid}>{children}</section>}function Card({item,images,onEdit,onArchive}){return <article style={s.card}><div style={s.images}>{images.filter(Boolean).map((src,index)=><img key={src} src={src} alt={`${item.title||"Contenuto"} ${index+1}`}/>)}</div><h3>{item.title||"Senza titolo"}</h3><p>Ordine {item.order} · {item.active?"Attivo":"Archiviato"} · {item.visible?"Visibile":"Nascosto"}</p><button onClick={onEdit}>Modifica</button>{item.active?<button onClick={onArchive}>Archivia</button>:null}</article>}
const s={page:{maxWidth:1200,margin:"auto",padding:24},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20},kicker:{textTransform:"uppercase",letterSpacing:3},card:{display:"grid",gap:12,background:"#fffaf5",padding:22,borderRadius:24,margin:"20px 0"},label:{display:"grid",gap:6,fontWeight:700},input:{padding:12,borderRadius:12,border:"1px solid #cfc3bb"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16},images:{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:4},};
