export const legalConfiguration = Object.freeze({
  effectiveDate: "08/08/2026",
  privacyVersion: "privacy-2026-08-08",
  cookieVersion: "cookie-2026-08-08",
  email: "info@medeabeautylounge.com",
  phone: "091 6727291",
});

export const privacySections = Object.freeze([
  { title: "1. Titolare del trattamento e contatti", paragraphs: ["Il titolare del trattamento è Medea Beauty Lounge, con sede in Via Giorgio D'Antiochia, 6 – Palermo, P. IVA 07118580823. Per richieste relative ai dati personali è possibile scrivere a info@medeabeautylounge.com o contattare il numero 091 6727291."] },
  { title: "2. Ambito dell’informativa", paragraphs: ["Questa informativa si applica al sito Medea Beauty Lounge, all’app mobile MedeaBeautyMobileV2, alle aree riservate e al sistema di richiesta e gestione degli appuntamenti. Sito e app condividono i servizi Firebase e gli stessi processi gestionali, pur usando tecnologie di memorizzazione diverse."] },
  { title: "3. Dati trattati", paragraphs: [
    "Dati di navigazione e sicurezza: indirizzo IP trattato temporaneamente dai fornitori, tipo di dispositivo e browser, identificativi di richiesta, eventi tecnici, esiti di sicurezza, identificativi sottoposti a hash per il rate limiting e token o materiale di attestazione App Check.",
    "Dati account e autenticazione: UID Firebase, email, password gestita da Firebase Authentication e non leggibile da Medea, nome visualizzato, stato di verifica email, ruolo, stato dell’account, data di creazione e ultimo accesso.",
    "Dati cliente: nome e cognome, telefono, lingua preferita, eventuale data di nascita e preferenze di notifica configurate nell’area personale.",
    "BookingForm guest: nome, cognome, email, telefono, trattamento e operatore scelti, data e ora richieste, messaggio facoltativo, provenienza della richiesta, identificativo idempotente, data di accettazione e versione dell’informativa.",
    "Appuntamenti e Beauty Paths: trattamento, operatore, data, durata prevista, stato, note operative facoltative, collegamenti tra appuntamenti, percorsi e relativi eventi. La durata riserva lo spazio previsto in agenda e non misura automaticamente il tempo effettivo del servizio.",
    "Dati staff e contenuti: nome professionale, ruolo, visibilità, stato, ordine, collegamento facoltativo all’account e immagine profilo; immagini e contenuti pubblicati nelle sezioni informative o gallery.",
    "Notifiche e comunicazioni: il sistema conserva preferenze e record tecnici interni per evitare duplicazioni. Non risultano attualmente integrati invii push, SMS o marketing automatico. Firebase Authentication può inviare email tecniche di verifica e ripristino password.",
  ] },
  { title: "4. Note operative e categorie particolari di dati", paragraphs: ["I campi note sono destinati a informazioni organizzative e relative al servizio estetico. Non devono essere inseriti dati sanitari, diagnosi o altre categorie particolari di dati non necessarie. Se un servizio richiedesse in futuro tali informazioni, Medea dovrà definire preventivamente una base giuridica adeguata, un’informativa specifica e le eventuali modalità di consenso esplicito."] },
  { title: "5. Finalità", paragraphs: ["I dati sono trattati per creare e gestire account; verificare identità, ruoli e autorizzazioni; rispondere alle richieste; organizzare appuntamenti, disponibilità, Beauty Paths e attività dello staff; gestire contenuti e immagini; inviare comunicazioni tecniche richieste; prevenire abusi, replay e doppie prenotazioni; garantire sicurezza, continuità e manutenzione; adempiere a obblighi di legge e tutelare i diritti del titolare."] },
  { title: "6. Basi giuridiche", paragraphs: ["Le attività richieste dall’utente e la gestione dell’appuntamento si basano sull’esecuzione di misure precontrattuali o contrattuali. Gli adempimenti amministrativi e fiscali si basano su obblighi legali. Sicurezza, prevenzione abusi, gestione tecnica e tutela dei diritti si basano sul legittimo interesse del titolare, bilanciato con i diritti degli interessati. Eventuali comunicazioni promozionali o funzionalità facoltative che richiedano consenso saranno attivate solo dopo una scelta separata e revocabile. La presa visione della Privacy Policy nel BookingForm documenta l’informativa applicabile e non viene usata come consenso indistinto a finalità ulteriori."] },
  { title: "7. Natura del conferimento", paragraphs: ["I dati indicati come obbligatori sono necessari per creare l’account, identificare la richiesta o gestire l’appuntamento; senza di essi la relativa funzione non può essere fornita. Messaggi, note, foto, data di nascita, preferenze e scelta di aprire WhatsApp sono facoltativi, salvo che diventino necessari per una specifica richiesta comunicata all’interessato."] },
  { title: "8. Destinatari e fornitori", paragraphs: ["Possono accedere ai dati soltanto titolare, personale autorizzato e fornitori necessari: Google/Firebase per Authentication, Firestore, Cloud Functions, Storage e App Check; Vercel per l’hosting del sito e i relativi log infrastrutturali; Apple e Google per le attestazioni App Check native quando abilitate. WhatsApp/Meta, Instagram e Google Maps ricevono dati solo quando l’utente sceglie di aprire i relativi servizi esterni. Non risultano integrati Analytics, Crashlytics, pixel pubblicitari o piattaforme di profilazione. I fornitori operano secondo i rispettivi ruoli e accordi sul trattamento applicabili."] },
  { title: "9. Trasferimenti fuori dallo SEE", paragraphs: ["Alcuni fornitori possono trattare dati fuori dallo Spazio Economico Europeo. Firebase Authentication opera anche da infrastrutture negli Stati Uniti, mentre altri servizi Firebase e i servizi di Vercel, Apple, Google e Meta possono usare infrastrutture globali. I trasferimenti devono avvenire tramite decisioni di adeguatezza, clausole contrattuali standard o altre garanzie previste dal GDPR, secondo gli accordi applicabili con ciascun fornitore."] },
  { title: "10. Conservazione", paragraphs: ["I dati sono conservati per il tempo necessario alla gestione della richiesta, dell’account, dell’appuntamento o del Beauty Path e successivamente per obblighi amministrativi, fiscali, sicurezza o tutela dei diritti. Account e profili restano fino a richiesta di cancellazione o cessazione del rapporto, fatti salvi obblighi e dati storici da conservare. I log seguono i periodi tecnici dei fornitori; i documenti di rate limiting hanno scadenza tecnica breve. I token App Check hanno durata limitata e, quando è usata la protezione replay, Firebase può conservare i token già consumati fino a 30 giorni. Alla scadenza i dati vengono cancellati, anonimizzati o resi non più direttamente riferibili, quando tecnicamente e legalmente possibile."] },
  { title: "11. Sicurezza e decisioni automatizzate", paragraphs: ["Sono impiegati autenticazione, verifica email, autorizzazioni per ruolo, regole Firestore e Storage, Callable Functions protette, App Check, rate limiting, idempotenza, transazioni e logging senza contenuti personali. I controlli automatici di sicurezza possono bloccare temporaneamente richieste anomale, ma non producono decisioni con effetti giuridici o analogamente significativi e non viene effettuata profilazione commerciale."] },
  { title: "12. Diritti e reclamo", paragraphs: ["L’interessato può chiedere accesso, rettifica, cancellazione, limitazione, portabilità, opposizione e revoca di un eventuale consenso, nei casi previsti dal GDPR, scrivendo a info@medeabeautylounge.com. È inoltre possibile proporre reclamo al Garante per la protezione dei dati personali tramite www.garanteprivacy.it. Prima di dare seguito alla richiesta può essere necessario verificare l’identità del richiedente."] },
  { title: "13. Minori", paragraphs: ["I canali digitali non sono progettati per raccogliere autonomamente dati di minori. Le richieste relative a un minore devono essere effettuate o autorizzate da chi esercita la responsabilità genitoriale, secondo la normativa applicabile. Chi ritiene che siano stati forniti dati di un minore senza adeguata autorizzazione può contattare il titolare per le verifiche necessarie."] },
  { title: "14. Modifiche", paragraphs: ["L’informativa può essere aggiornata quando cambiano servizi, trattamenti o obblighi normativi. La nuova versione e la data di efficacia saranno pubblicate nel sito e nell’app; quando necessario sarà richiesta una nuova presa visione."] },
]);

export const webCookieSections = Object.freeze([
  { title: "1. Ambito", paragraphs: ["Questa Cookie Policy riguarda il sito web Medea Beauty Lounge. L’app mobile nativa non usa cookie web: utilizza invece lo storage protetto o interno dei sistemi operativi e dei moduli Firebase, descritto nella Privacy Policy e nella sezione 4."] },
  { title: "2. Strumenti effettivamente presenti", paragraphs: ["Nel codice non risultano integrati Google Analytics, Firebase Analytics, Vercel Analytics, Crashlytics, Sentry, pixel pubblicitari o strumenti di profilazione. Sono presenti Firebase Authentication per la sessione dell’area riservata e Firebase App Check con reCAPTCHA Enterprise, quando abilitato, per proteggere le richieste. Vercel fornisce l’hosting e può produrre log infrastrutturali, ma il progetto non include lo script Vercel Analytics."] },
  { title: "3. Cookie e storage necessari", paragraphs: ["Firebase Authentication può usare IndexedDB e localStorage del browser per mantenere la sessione autenticata. Le chiavi e il formato sono gestiti dal relativo SDK e possono variare con browser e versione; la sessione permane normalmente fino al logout, alla revoca o alla cancellazione dei dati del browser.", "Quando App Check web è abilitato, reCAPTCHA Enterprise può impostare il cookie necessario _GRECAPTCHA per l’analisi del rischio. La durata è determinata dal fornitore e dalla configurazione del servizio. I token App Check hanno comunque una validità tecnica limitata, non superiore a sette giorni; quelli usati per la protezione replay possono essere conservati da Firebase fino a 30 giorni.", "Il sito usa inoltre memoria temporanea JavaScript per stato del form, navigazione e richieste. I dati digitati nel BookingForm non vengono salvati dal codice applicativo in localStorage o cookie prima dell’invio."] },
  { title: "4. Storage dell’app mobile", paragraphs: ["La build mobile usa la persistenza nativa di Firebase Authentication per mantenere la sessione e gli archivi interni necessari al funzionamento degli SDK. La dipendenza AsyncStorage è installata, ma l’audit non ha rilevato scritture applicative dirette. App Check può usare identificativi e token di attestazione gestiti dai sistemi Apple/Google e da Firebase."] },
  { title: "5. Servizi esterni", paragraphs: ["WhatsApp, Instagram e Google Maps sono raggiunti tramite link: non vengono caricati come widget incorporati e ricevono informazioni soltanto dopo l’azione dell’utente. Da quel momento si applicano le policy del servizio scelto. Vercel e Firebase possono trattare dati tecnici di rete necessari a erogare e proteggere il servizio."] },
  { title: "6. Base giuridica e consenso", paragraphs: ["Cookie e strumenti descritti sono strettamente necessari per autenticazione, sicurezza e fornitura delle funzioni richieste; sono utilizzati sulla base della necessità tecnica e del legittimo interesse alla sicurezza, senza consenso preventivo, fermo l’obbligo di informativa. Non sono attualmente usati cookie analytics non esenti, marketing o profilazione. Per questo non viene mostrato un banner di consenso. Se saranno introdotti strumenti non necessari, resteranno disattivati fino a consenso e sarà aggiunto un sistema di scelta e revoca."] },
  { title: "7. Gestione e durata", paragraphs: ["L’utente può cancellare cookie e storage dalle impostazioni del browser e può terminare la sessione con il logout. Il blocco degli strumenti strettamente necessari può impedire login, App Check o BookingForm. Le durate effettive possono dipendere dal browser e dal fornitore; questa policy sarà aggiornata se cambieranno configurazioni o servizi."] },
  { title: "8. Contatti", paragraphs: ["Per informazioni è possibile scrivere a info@medeabeautylounge.com. Per il trattamento dei dati collegato a cookie e storage si applica anche la Privacy Policy."] },
]);
